<?php

/**
 * @Project NUKEVIET 3.4
 * @Author VINADES.,JSC (contact@vinades.vn)
 * @Copyright (C) 2010 - 2012 VINADES.,JSC. All rights reserved
 * @Createdate Sun, 08 Apr 2012 00:00:00 GMT GMT
 */

if(!defined('NV_IS_FILE_SITEINFO'))die('Stop!!!');$lang_siteinfo=nv_get_lang_module($mod);list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_rows` WHERE `status`= 1 AND `publtime` < ".NV_CURRENTTIME." AND (`exptime`=0 OR `exptime`>".NV_CURRENTTIME.")"));if($number>0){$siteinfo[]=array('key'=>$lang_siteinfo['siteinfo_publtime'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_rows` WHERE `status`= 0 AND `publtime` < ".NV_CURRENTTIME." AND (`exptime`=0 OR `exptime`>".NV_CURRENTTIME.")"));if($number>0){$siteinfo[]=array('key'=>$lang_siteinfo['siteinfo_pending'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_rows` WHERE `exptime` > 0 AND `exptime`<".NV_CURRENTTIME.""));if($number>0){$siteinfo[]=array('key'=>$lang_siteinfo['siteinfo_expired'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_rows` WHERE `status` = 1 AND `exptime`>".NV_CURRENTTIME.""));if($number>0){$siteinfo[]=array('key'=>$lang_siteinfo['siteinfo_exptime'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_comments_".NV_LANG_DATA."` WHERE `status` = 1"));if($number>0){$siteinfo[]=array('key'=>$lang_siteinfo['siteinfo_comment'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_orders`"));if($number>0){$siteinfo[]=array('key'=>$lang_siteinfo['siteinfo_order'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_comments_".NV_LANG_DATA."` WHERE `status` = 0"));if($number>0){$pendinginfo[]=array('key'=>$lang_siteinfo['siteinfo_comment_pending'],'value'=>$number);}list($number)=$db->sql_fetchrow($db->sql_query("SELECT COUNT(*) AS number FROM `".$db_config['prefix']."_".$mod_data."_orders` WHERE `view` = 0 "));if($number>0){$pendinginfo[]=array('key'=>$lang_siteinfo['siteinfo_order_noview'],'value'=>$number,'link'=>NV_BASE_ADMINURL."index.php?".NV_NAME_VARIABLE."=".$mod."&amp;".NV_OP_VARIABLE."=order");}

?>